// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TomorrowlandSessionPlanner.Core.DBContext;

#nullable disable

namespace TomorrowlandSessionPlanner.Migrations
{
    [DbContext(typeof(TmldbContext))]
    partial class TmldbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("TomorrowlandSessionPlanner.Models.Dj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Djs");
                });

            modelBuilder.Entity("TomorrowlandSessionPlanner.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DjId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DjId");

                    b.HasIndex("StageId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TomorrowlandSessionPlanner.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("TomorrowlandSessionPlanner.Models.Session", b =>
                {
                    b.HasOne("TomorrowlandSessionPlanner.Models.Dj", "Dj")
                        .WithMany("Sessions")
                        .HasForeignKey("DjId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TomorrowlandSessionPlanner.Models.Stage", "Stage")
                        .WithMany("Sessions")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dj");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("TomorrowlandSessionPlanner.Models.Dj", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TomorrowlandSessionPlanner.Models.Stage", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
